# Generated by Django 5.0.7 on 2024-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='course',
            field=models.CharField(choices=[('AOOP', 'Advanced Object - Oriented Programming'), ('PFSD', 'Python Full Stack Development')], max_length=50),
        ),
    ]
